
service: bnb-miner

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    privateKey: ${s3:bucketname/privateKey}
    publicKey: ${s3:bucketname/publicKey}
    publicKeyDestination: ${s3:bucketname/publicKeyDestination}


functions:
  sell:
    handler: handler.sell
    events:
          - schedule:
              rate: cron(0 17 ? * MON *)
  compound:
    handler: handler.compound
    events:
          - schedule:
              rate: cron(0 */8 ? * TUE,WED,THU,FRI,SAT,SUN *)
